const ObjectTypes = {
    PERSON: "person",
    BICYCLE: "bicycle",
    CAR: "car",
    MOTORCYCLE: "motorcycle",
    AIRPLANE: "airplane",
    BUS: "bus",
    TRAIN: "train",
    TRUCK: "truck",
    BOAT: "boat",
    TRAFFIC_LIGHT: "traffic light",
    FIRE_HYDRANT: "fire hydrant",
    STOP_SIGN: "stop sign",
    PARKING_METER: "parking meter",
    BENCH: "bench",
    BIRD: "bird",
    CAT: "cat",
    DOG: "dog",
    HORSE: "horse",
    SHEEP: "sheep",
    COW: "cow",
    ELEPHANT: "elephant",
    BEAR: "bear",
    ZEBRA: "zebra",
    GIRAFFE: "giraffe",
    BACKPACK: "backpack",
    UMBRELLA: "umbrella",
    HANDBAG: "handbag",
    TIE: "tie",
    SUITCASE: "suitcase",
    FRISBEE: "frisbee",
    SKIS: "skis",
    SNOWBOARD: "snowboard",
    SPORTS_BALL: "sports ball",
    KITE: "kite",
    BASEBALL_BAT: "baseball bat",
    BASEBALL_GLOVE: "baseball glove",
    SKATEBOARD: "skateboard",
    SURFBOARD: "surfboard",
    TENNIS_RACKET: "tennis racket",
    BOTTLE: "bottle",
    WINE_GLASS: "wine glass",
    CUP: "cup",
    FORK: "fork",
    KNIFE: "knife",
    SPOON: "spoon",
    BOWL: "bowl",
    BANANA: "banana",
    APPLE: "apple",
    SANDWICH: "sandwich",
    ORANGE: "orange",
    BROCCOLI: "broccoli",
    CARROT: "carrot",
    HOT_DOG: "hot dog",
    PIZZA: "pizza",
    DONUT: "donut",
    CAKE: "cake",
    CHAIR: "chair",
    COUCH: "couch",
    POTTED_PLANT: "potted plant",
    BED: "bed",
    DINING_TABLE: "dining table",
    TOILET: "toilet",
    TV: "tv",
    LAPTOP: "laptop",
    MOUSE: "mouse",
    REMOTE: "remote",
    KEYBOARD: "keyboard",
    CELL_PHONE: "cell phone",
    MICROWAVE: "microwave",
    OVEN: "oven",
    TOASTER: "toaster",
    SINK: "sink",
    REFRIGERATOR: "refrigerator",
    BOOK: "book",
    CLOCK: "clock",
    VASE: "vase",
    SCISSORS: "scissors",
    TEDDY_BEAR: "teddy bear",
    HAIR_DRIER: "hair drier",
    TOOTHBRUSH: "toothbrush"
};

const ObjectTypesInTurkish = {
    PERSON: "Kişi",
    BICYCLE: "Bisiklet",
    CAR: "Araba",
    MOTORCYCLE: "Motorsiklet",
    AIRPLANE: "Uçak",
    BUS: "Otobüs",
    TRAIN: "Tren",
    TRUCK: "Kamyon",
    BOAT: "Tekne",
    TRAFFIC_LIGHT: "Trafik Lambası",
    FIRE_HYDRANT: "İtfaiye Hidrantı",
    STOP_SIGN: "Dur Levhası",
    PARKING_METER: "Park Metresi",
    BENCH: "Benk",
    BIRD: "Kuş",
    CAT: "Kedi",
    DOG: "Köpek",
    HORSE: "At",
    SHEEP: "Koyun",
    COW: "İnek",
    ELEPHANT: "Fil",
    BEAR: "Ayı",
    ZEBRA: "Zebra",
    GIRAFFE: "Zürafa",
    BACKPACK: "Sırt Çantası",
    UMBRELLA: "Şemsiye",
    HANDBAG: "Çanta",
    TIE: "Kravat",
    SUITCASE: "Valiz",
    FRISBEE: "Frizbi",
    SKIS: "Kızak",
    SNOWBOARD: "Kar Tahtası",
    SPORTS_BALL: "Spor Topu",
    KITE: "Uçurtma",
    BASEBALL_BAT: "Beyzbol Sopası",
    BASEBALL_GLOVE: "Beyzbol Eldiveni",
    SKATEBOARD: "Paten",
    SURFBOARD: "Sörf Tahtası",
    TENNIS_RACKET: "Tenis Raketi",
    BOTTLE: "Şişe",
    WINE_GLASS: "Şarap Kadehi",
    CUP: "Kupa",
    FORK: "Çatal",
    KNIFE: "Bıçak",
    SPOON: "Kaşık",
    BOWL: "Kase",
    BANANA: "Muz",
    APPLE: "Elma",
    SANDWICH: "Sandviç",
    ORANGE: "Portakal",
    BROCCOLI: "Brokoli",
    CARROT: "Havuç",
    HOT_DOG: "Sosisli Sandviç",
    PIZZA: "Pizza",
    DONUT: "Doughnut",
    CAKE: "Pasta",
    CHAIR: "Sandalye",
    COUCH: "Kanepe",
    POTTED_PLANT: "Saksı Bitkisi",
    BED: "Yatak",
    DINING_TABLE: "Yemek Masası",
    TOILET: "Tuvalet",
    TV: "Televizyon",
    LAPTOP: "Dizüstü Bilgisayar",
    MOUSE: "Fare",
    REMOTE: "Uzaktan Kumanda",
    KEYBOARD: "Klavye",
    CELL_PHONE: "Telefon",
    MICROWAVE: "Mikrodalga",
    OVEN: "Fırın",
    TOASTER: "Tost Makinesi",
    SINK: "Lavabo",
    REFRIGERATOR: "Buzdolabı",
    BOOK: "Kitap",
    CLOCK: "Saat",
    VASE: "Vazo",
    SCISSORS: "Makas",
    TEDDY_BEAR: "Peluş Ayı",
    HAIR_DRIER: "Saç Kurutma Makinesi",
    TOOTHBRUSH: "Diş Fırçası"
};

module.exports = { ObjectTypes, ObjectTypesInTurkish };
